# Code for removing STRESS based outliers from training set (MACE MLIP)
# For any errors, kindly reach out to me at asifaltafshah9@gmail.com

import os
import shutil
import numpy as np

# Threshold for Stress
SThre = 40

# Reading the training set containing outliers, generated by combining many optimization trajectories
X = nlread('/home/OriginalTrainingSet.hdf5', TrainingSet)[0]
print("Original training set size = ", X.sampleSize())

# Initializing an array for storing indices of outliers in X
indices = np.zeros(X.sampleSize())
j=0
for i in range(X.sampleSize()):
    STh = np.max(np.absolute(X.configurations().stresses(i).inUnitsOf(GPa)))
    if STh > SThre:
        indices[j] = i
        j+=1

# Removing unwanted zeros in the end of array
last = np.where(indices != 0)[0][-1]
indices = indices[:last + 1]
print("Number of outliers in initial training set = ", len(indices))
print("Outliers = ", indices)

# Calculating distance between consecutive outliers
Nindices = np.empty_like(indices)
Nindices[0] = indices[0]
Nindices[1:] = indices[1:] - (indices[:-1] + 1)
print("New indices", Nindices)

# Removing outliers from training set and saving non-outliers between outliers as training set
j=1
for idx, i in enumerate(Nindices):
    if int(i) != 0:
        Sav, For = X.trainTestSplit(train_size = int(i), shuffle=False)
        Temp, For = For.trainTestSplit(train_size = int(1), shuffle=False)
        nlsave(f"/home/Split/NonOutlierTrainingData{j}.hdf5", Sav)
        j+=1
        X = For
        if idx == len(Nindices)-1 and indices[idx] != len(X)-1:
            nlsave(f"/home/Split/NonOutlierTrainingData{j}.hdf5", X)
    if int(i) == 0 and idx!= len(Nindices)-1:
        Temp, X = X.trainTestSplit(train_size = int(1), shuffle=False)

# Combining all non-outlier training sets from folder Train
input_dir = "/home/Split/"
TSets = []

for fname in sorted(os.listdir(input_dir)):
    training_data = nlread(input_dir + fname, TrainingSet)[0]
    TSets.append(training_data)

force_field_training_set_generator = ForceFieldTrainingSetGenerator(
    filename='/home/Split/AllTrainingSet.hdf5',
    object_id='fftsg',
    training_sets=TSets,
    calculator=None,
    calculate_stress=None,
)
force_field_training_set_generator.update()
generated_trainingset = force_field_training_set_generator.generatedTrainingSet()
nlsave("/home/Split/AllTrainingSet.hdf5", generated_trainingset)
Y = nlread('/home/Split/AllTrainingSet.hdf5', TrainingSet)[0]
print("Final training set size = ", Y.sampleSize())

# Rechecking if there is any higher stress configuration in final training set after outliers are removed
X = nlread('/home/Split/AllTrainingSet.hdf5', TrainingSet)[0]
indices = []
j=0
for i in range(X.sampleSize()):
    STh = np.max(np.absolute(X.configurations().stresses(i).inUnitsOf(GPa)))
    if STh > SThre:
        indices.append(i)
        j+=1

print("Number of outliers in final training set = ", j)
if len(indices) > 0:
    print("Outliers = ", indices)
else:
    print("No outliers found :)")

